# Generated by Django 5.1.1 on 2024-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, db_collation='utf8_unicode_ci', max_length=250, null=True)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'short_names',
                'managed': False,
            },
        ),
    ]
